apiVersion: apps/v1
kind: Deployment
metadata: 
  name: mysql
spec: 
  selector: 
    matchLabels: 
      app: mysql-server
      tier: backend
      track: stable
  replicas: 1
  template: 
    metadata: 
      labels: 
        app: mysql-server
        tier: backend
        track: stable
    spec:
      containers: 
        - name: mysql
          image: "gcr.io/testing-project-272008/mysql"
          ports: 
            - name: http
              containerPort: 3306
